name: Cloudflare Pages

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose an environment to deploy to: <next|prod>"
        required: true
        default: "next"
        type: choice
        options:
          - next
          - prod

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_DISCORD_BOT_ID: "970714810905936022"
      VITE_DISCORD_BOT_REDIRECT: "https://api.pixelbattle.fun/login"
      VITE_BACKEND: "https://api.pixelbattle.fun"
      NODE_VERSION: "22.18"
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"

      - run: yarn install --frozen-lockfile
      - run: yarn build

      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./dist
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: build-output
          path: ./dist

      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=pixelbattle-${{ github.event.inputs.environment }}
